version: "3"

services:
  api:
    build: .
    container_name: haiti-mspp-api
    restart: always
    networks: 
      - default
    ports:
      - 5000:5000
    volumes: 
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: haiti-mspp-postgres
    restart: always
    networks: 
      - default
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - .env

volumes:
  postgres_data: